// <auto-generated />
using System;
using GanheFacil.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GanheFacil.Migrations
{
    [DbContext(typeof(GanheFacilContext))]
    [Migration("20230714132604_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GanheFacil.Models.NumeroSorteado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int?>("SorteioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SorteioId");

                    b.ToTable("NumeroSorteados", (string)null);
                });

            modelBuilder.Entity("GanheFacil.Models.Resultado", b =>
                {
                    b.Property<DateTime>("DataSorteio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPremio")
                        .HasColumnType("decimal(18, 2)");

                    b.ToTable("Resultados", (string)null);
                });

            modelBuilder.Entity("GanheFacil.Models.Sorteio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataSorteio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("NumerosSorteados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoJogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sorteios", (string)null);
                });

            modelBuilder.Entity("GanheFacil.Models.NumeroSorteado", b =>
                {
                    b.HasOne("GanheFacil.Models.Sorteio", null)
                        .WithMany("ListaNumeroSorteados")
                        .HasForeignKey("SorteioId");
                });

            modelBuilder.Entity("GanheFacil.Models.Sorteio", b =>
                {
                    b.Navigation("ListaNumeroSorteados");
                });
#pragma warning restore 612, 618
        }
    }
}
